create type TweetMessageTypeuuid as closed {
        tweetid: uuid,
        message_text: string
};

create type TweetMessageType as closed {
        tweetid: string,
        message_text: string
};

create dataset TweetMessageuuids(TweetMessageTypeuuid)
primary key tweetid autogenerated;

create function NearbyTweetsContainingText(text) {
 ( SELECT current_datetime() as timestamp, message.message_text as message
  FROM TweetMessageuuids message
  WHERE contains(message.message_text, text))
};

insert into TweetMessageuuids(
[{"message_text":"Live man"},
{"message_text":"Dead man"},
{"message_text":"Walking man"},
{"message_text":"Good man"}]
);
